### ISSUE TITLE
 `test mode`  code ?

### ISSUE THREAD

**Issue by lsq357** [craffel/mad#1]
Hi! Thanks for your source code!
In the appendix of [paper](https://arxiv.org/abs/1704.00784), the `test mode` and `train mode` is diffenent, but  here I can't see the `test mode` code!
It only has `train mode` code in [here](https://github.com/craffel/mad/blob/master/example_decoder.py) and  TensorFlow `tf.contrib.seq2seq` module!
Or, maybe I loss some detailed code?
How to modify code to distinguish `train mode` and `test mode`?

**Comment by craffel** [comment]
"Test" mode corresponds to `mode = 'hard'`.
